language: node_js
node_js:
- '7'
sudo: required
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
script:
  - google-chrome-stable --headless --disable-gpu --dump-dom "http://localhost:8000 > test.html
  - ./push-data.sh
